export enum Currency {
  GBP = 'GBP',
  USD = 'USD',
  EUR = 'EUR',
  JPY = 'JPY',
}

export const CURRENCY_SIGNS: Record<Currency, string> = {
  [Currency.GBP]: '£',
  [Currency.USD]: '$',
  [Currency.EUR]: '€',
  [Currency.JPY]: '¥',
};

export const NUMBER_OF_VISIBLE_POCKETS = 3;

export const FETCH_HISTORY_REQUESTED = 'FETCH_HISTORY_REQUESTED';
export const FETCH_HISTORY_SUCCEEDED = 'FETCH_HISTORY_SUCCEEDED';
export const FETCH_HISTORY_FAILED = 'FETCH_HISTORY_FAILED';
export const SET_HISTORY = 'SET_HISTORY';

export const FETCH_POCKETS_REQUESTED = 'FETCH_POCKETS_REQUESTED';
export const FETCH_POCKETS_SUCCEEDED = 'FETCH_POCKETS_SUCCEEDED';
export const FETCH_POCKETS_FAILED = 'FETCH_POCKETS_FAILED';
export const SET_ACTIVE_POCKET_ID = 'SET_ACTIVE_POCKET_ID';
export const SET_POCKETS = 'SET_POCKETS';

export const FETCH_RATES_REQUESTED = 'FETCH_RATES_REQUESTED';
export const FETCH_RATES_SUCCEEDED = 'FETCH_RATES_SUCCEEDED';
export const FETCH_RATES_FAILED = 'FETCH_RATES_FAILED';

export const EXCHANGE = 'EXCHANGE';
export const SET_EXCHANGE_ERROR = 'SET_EXCHANGE_ERROR';
export const SET_WRITE_OFF_POCKET_ID = 'SET_WRITE_OFF_POCKET_ID';
export const SET_RECEIVE_POCKET_ID = 'SET_RECEIVE_POCKET_ID';
export const SET_WRITE_OFF_AMOUNT = 'SET_WRITE_OFF_AMOUNT';
export const SET_RECEIVE_AMOUNT = 'SET_RECEIVE_AMOUNT';
